fixing pipeline

diff --git a/.github/workflows/github-ci.yml b/.github/workflows/github-ci.yml
--- a/.github/workflows/github-ci.yml
+++ b/.github/workflows/github-ci.yml
@@ -337,6 +337,19 @@ jobs :
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Debug workspace before SCP
+        run: |
+          echo "Current directory:"
+          pwd
+          echo "Root files:"
+          ls -la
+          echo "docker-compose-stage.yml:"
+          ls -la docker-compose-stage.yml || echo "missing"
+          echo "infra folder:"
+          ls -la infra || echo "infra missing"
+          echo "infra recursive:"
+          ls -R infra || echo "infra recursive missing"
+
       - name: copy docker-compose-stage.yml and infra/ to stage server
         uses: appleboy/scp-action@v0.1.7
         with:
